### ISSUE TITLE
Visual Studio edition

### ISSUE THREAD

**Issue by sungongjian** [kdarkhan/vscode-mips-support#1]
Hello! 
Do you have Visual Studio edition of this extension?
I mean Visual Studio, **not** Visual Studio Code. 

Thanks a lot!

**Comment by kdarkhan** [comment]
HI @sungongjian,
No I don't have it. I don't use Visual Studio and by checking it quickly it seems that the structure of the extensions is very different there. I will not be able to extend this easily to convert it.
