### ISSUE TITLE
Using space instead of tab when inserting snippets

### ISSUE THREAD

**Issue by Gallium70** [kdarkhan/vscode-mips-support#6]
Snippets are great, but maybe it's better using 4 spaces instead of hard tabs('\t'); it's even better if it's configurable. Thx!

**Comment by kdarkhan** [comment]
@Gallium70, the way snippets are implemented there is no way to configure it. As you can see from [here](https://github.com/kdarkhan/vscode-mips-support/blob/master/snippets/snippets.json) the snippets definitions are static. This logic should be handled on VSCode side.

There is already an issue which describes it [here](https://github.com/microsoft/vscode/issues/5355). The translation happens only for leading tabs, but all tabs in my snippets are non-leading, so replacement does not happen.

**Comment by Gallium70** [comment]
I just realized that simply replace tab with 4 spaces would break the alignment. 😞 Thanks a lot for reply and sending PR to VSCode.
