### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by spoenemann** [kdarkhan/vscode-mips-support#8]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) **on or before January 8, 2021**. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by kdarkhan** [comment]
I just signed the agreement. Thanks!

**Comment by spoenemann** [comment]
Hi @kdarkhan, thanks for responding to this! I see you have created an Eclipse account, but it is not linked with your open-vsx.org account yet. Have you gone through step 2 of the publishing docs?
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#2-log-in-and-sign-the-publisher-agreement

**Comment by kdarkhan** [comment]
Ah, my bad. I only did the first step. I just linked the account. I assume I would not need to do other steps since I have already published my extension, right?

**Comment by spoenemann** [comment]
Looks good now :+1:
